### ISSUE TITLE
Downloading viral contigs file

### ISSUE THREAD

**Issue by deminatanja** [cmsantosm/SpatioTemporalViromes#1]
Hi, 
is it possible to download the vOTU_dereplicated.fa file as a file rather than viewing it in the browser? If I press "Download" button, it is shown in the browser and I suspect not all data may be visible or might take really long to display all. Do I understand correctly that this file contains viral contigs identified in the study?
Best regards,
Tatiana

**Comment by cmsantosm** [comment]
Hi Tatiana,

Probably the easiest way to do it is to use wget to download the file:

`wget https://github.com/cmsantosm/SpatioTemporalViromes/raw/master/vOTU_dereplicated.fa`

And yes, this file contains the dereplicated viral contigs identified in the study.

Best,
Christian

**Comment by deminatanja** [comment]
Hi Christian,
Right, thank you, this works well.
Best,
Tatiana
